#!/usr/bin/env perl

use strict;
use warnings;

use LWP::UserAgent;
use pQuery;

my $query = join ' ' => @ARGV;

my $ua = LWP::UserAgent->new(agent => 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_7_3) AppleWebKit/536.5 (KHTML, like Gecko) Chrome/19.0.1084.30 Safari/536.5');
$ua->proxy(http => $ENV{http_proxy});

my $response = $ua->get("http://www.google.com/search?q=$query");
my $result   = pQuery( $response->decoded_content )->find('#topstuff .r b')->html;
print "$result\n";
